# Generated by Django 4.1.7 on 2023-02-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_point', models.IntegerField()),
                ('image', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'alpha_character',
            },
        ),
    ]
