# Generated by Django 4.1.7 on 2023-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_origin',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
