# Generated by Django 4.1.7 on 2023-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
