# Generated by Django 4.1.7 on 2023-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('done', 'done')], default='ready', max_length=32),
        ),
    ]
