# Generated by Django 4.1.7 on 2023-02-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spacename', models.CharField(max_length=256, null=True)),
                ('point', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'alpha_member',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'ready'), ('clicked', 'clicked'), ('done', 'done')], default='ready', max_length=32)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.mission')),
            ],
            options={
                'db_table': 'alpha_log',
            },
        ),
    ]
