# Generated by Django 4.1.7 on 2023-02-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_managers_member_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
