# Generated by Django 4.1.7 on 2023-02-20 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character', '0001_initial'),
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', 'unused'), ('used', 'used')], default='unused', max_length=128)),
                ('point', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.planet')),
            ],
            options={
                'db_table': 'detail',
            },
        ),
    ]
