# Generated by Django 4.1.7 on 2023-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.CharField(choices=[('unready', 'unready'), ('unused', 'unused'), ('used', 'used')], default='unready', max_length=128),
        ),
    ]
